apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newrelic-apm-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://newrelic.github.io/k8s-agents-operator
    chart: k8s-agents-operator
    targetRevision: 0.43.0
    helm:
      values: |
        admissionWebhooks:
          autoGenerateCert:
            enabled: false
            recreate: false
          certManager:
            enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: newrelic

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
