apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        resource.opentelemetry.io/service.name: "api-gateway"
        resource.opentelemetry.io/service.namespace: "ecommerce"
    spec:
      containers:
        - name: order-service
          image: dheerajkadve/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: ORDER_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret
                  key: POSTGRES_PASSWORD
            - name: CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: CART_SERVICE_URL
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: INVENTORY_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: PAYMENT_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: NOTIFICATION_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce-devops
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: order-service
