replicaCount: 1
namespace: ecommerce-devops

image:
  repository: dheerajkadve/cart-service
  tag: "12"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8083
  targetPort: 8083

containerPort: 8083
configMapName: ecommerce-config
secretName: ecommerce-secret

envFromConfigMap:
  - name: SPRING_PROFILES_ACTIVE
    key: SPRING_PROFILES_ACTIVE
  - name: SPRING_DATASOURCE_URL
    key: CART_DB_URL

envFromSecret:
  - name: SPRING_DATASOURCE_USERNAME
    key: POSTGRES_USER
  - name: SPRING_DATASOURCE_PASSWORD
    key: POSTGRES_PASSWORD

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
