replicaCount: 1
namespace: ecommerce-devops

image:
  repository: dheerajkadve/product-service
  tag: "13"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

containerPort: 8082
configMapName: ecommerce-config
secretName: ecommerce-secret

envFromConfigMap:
  - name: SPRING_PROFILES_ACTIVE
    key: SPRING_PROFILES_ACTIVE
  - name: SPRING_DATASOURCE_URL
    key: PRODUCT_DB_URL

envFromSecret:
  - name: SPRING_DATASOURCE_USERNAME
    key: POSTGRES_USER
  - name: SPRING_DATASOURCE_PASSWORD
    key: POSTGRES_PASSWORD

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
