replicaCount: 1

namespace: ecommerce-devops

image:
  repository: dheerajkadve/api-gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerPort: 8080

configMapName: ecommerce-config
secretName: ecommerce-secret

envFromConfigMap:
  - name: SPRING_PROFILES_ACTIVE
    key: SPRING_PROFILES_ACTIVE
  - name: USER_SERVICE_URL
    key: USER_SERVICE_URL
  - name: PRODUCT_SERVICE_URL
    key: PRODUCT_SERVICE_URL
  - name: CART_SERVICE_URL
    key: CART_SERVICE_URL
  - name: ORDER_SERVICE_URL
    key: ORDER_SERVICE_URL
  - name: INVENTORY_SERVICE_URL
    key: INVENTORY_SERVICE_URL
  - name: PAYMENT_SERVICE_URL
    key: PAYMENT_SERVICE_URL
  - name: NOTIFICATION_SERVICE_URL
    key: NOTIFICATION_SERVICE_URL

envFromSecret:
  []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
